databendlabs/helm-charts

.github/workflows/release.yml
=> [CI] Add release workflow

charts/databend-query/templates/ingress.yaml, charts/databend-query/values.yaml
=> add servicePort for ingress

charts/databend-query/README.md
=> [Doc] Append note for production

charts/databend-meta/README.md, charts/databend-meta/values.yaml, charts/databend-query/README.md
=> [Doc] add doc for meta

.github/workflows/release.yml
=> [CI] use chart-releaser-action

examples/meta-ha.yaml, examples/query-cluster-with-s3.yaml, examples/query-with-meta.yaml, examples/query-with-minio.yaml
Fixes: https://github.com/datafuselabs/helm-charts/issues/12
=> add examples

charts/databend-query/values.yaml
=> fix log path

charts/databend-meta/Chart.yaml, charts/databend-meta/values.yaml, charts/databend-query/Chart.yaml, charts/databend-query/README.md, charts/databend-query/templates/configmap.yaml, charts/databend-query/values.yaml
https://github.com/datafuselabs/databend/pull/4740
=> rename disk to fs for storage

charts/databend-meta/Chart.yaml, charts/databend-meta/templates/statefulset.yaml, charts/databend-meta/values.yaml, charts/databend-query/Chart.yaml, charts/databend-query/templates/configmap.yaml, charts/databend-query/templates/deployment.yaml, charts/databend-query/values.yaml
=> chore: upgrade query/meta version to 0.7.45

charts/databend-meta/Chart.yaml, charts/databend-meta/templates/statefulset.yaml, charts/databend-meta/values.yaml, charts/databend-query/Chart.lock, charts/databend-query/Chart.yaml, charts/databend-query/templates/deployment.yaml, charts/databend-query/values.yaml
=> add sidecars and initContainers

.github/workflows/release.yml
=> fix repo dep

charts/databend-meta/Chart.lock, charts/databend-meta/Chart.yaml, charts/databend-meta/templates/statefulset.yaml, charts/databend-meta/values.yaml
=> feat: add config for meta

charts/databend-meta/Chart.yaml, charts/databend-query/Chart.yaml
=> upgrade query and meta

charts/databend-query/README.md, charts/databend-query/templates/configmap.yaml, charts/databend-query/values.yaml, examples/query-cluster-with-s3.yaml, examples/query-with-meta.yaml
=> remove embedded enabled

charts/databend-query/Chart.yaml, charts/databend-query/templates/configmap.yaml
=> fix configmap

charts/databend-meta/Chart.lock, charts/databend-meta/Chart.yaml, charts/databend-meta/templates/servicemonitor.yaml, charts/databend-meta/templates/statefulset.yaml, charts/databend-meta/values.yaml, charts/databend-query/Chart.lock, charts/databend-query/Chart.yaml, charts/databend-query/templates/configmap.yaml, charts/databend-query/templates/servicemonitor.yaml, charts/databend-query/values.yaml, examples/query-with-minio.yaml
=> feat: add serviceMonitors

charts/databend-meta/Chart.yaml, charts/databend-query/Chart.yaml, charts/databend-query/templates/configmap.yaml, charts/databend-query/values.yaml
* remove old config `table_cache_enabled`
fix: https://github.com/datafuselabs/helm-charts/issues/36
=> fix: support extra args for query config

charts/databend-query/templates/configmap.yaml, charts/databend-query/values.yaml
=> feat: support gcs in query configmap

charts/databend-meta/Chart.yaml, charts/databend-meta/templates/service.yaml, charts/databend-meta/templates/statefulset.yaml
=> fix(meta): publish not ready addresses

charts/databend-meta/Chart.yaml, charts/databend-meta/templates/statefulset.yaml, charts/databend-meta/values.yaml
=> fix(meta): changes for bootstrap

charts/databend-query/values.yaml
fix: https://github.com/datafuselabs/helm-charts/issues/56
=> chore: add note for built-in user root

charts/databend-query/templates/configmap.yaml
daadded max_server_memory_usage and max_memory_limit_enabled for query configmap
=> daadded max_server_memory_usage and max_memory_limit_enabled

charts/databend-query/templates/configmap.yaml
@everpcpc it seems there are some the previous commit's syntax errors, by the way, does this repo support testing for, for example, syntax and other stuffs?
=> cache default value

charts/databend-query/templates/configmap.yaml
add pipeline funciton for configMap [cache]
fix https://github.com/datafuselabs/helm-charts/issues/66#issue-1681396257
=> 1. fix render error with helm v3.11

charts/databend-meta/Chart.yaml, charts/databend-meta/templates/poddisruptionbudget.yaml, charts/databend-meta/templates/statefulset.yaml
=> fix(meta): add PodDisruptionBudget & change podManagementPolicy to Parallel

charts/databend-query/Chart.yaml, charts/databend-query/templates/configmap.yaml
=> fix(query): extra config before query.users

charts/databend-query/Chart.yaml, charts/databend-query/templates/statefulset.yaml
Try to fix https://github.com/databendcloud/databend-py/issues/12
=> fix: databend query use statefulset

charts/databend-query/Chart.yaml, charts/databend-query/templates/service.yaml, charts/databend-query/values.yaml, examples/query-cluster-as-deployment.yaml
Support specify custom session affinity for query service.
=> feat(query): support custom session affinity

charts/databend-meta/Chart.yaml, charts/databend-meta/templates/statefulset.yaml, charts/databend-meta/values.yaml
We needed to customize some bootstrap behavior for our cluster, but I'm pushing these to you guys in case you want them upstream. Should cause no damage to current deployments
=> feat(meta): add startup script and new volume features

dashboards/query-runtime.json
Change datasource uid of promethues in dashboard/query-runtime.json to default promethues uid.
=> fix(dashboard): change datasource uid to default uid.
